# .github/workflows/ci.yml
name: CI/CD for Next.js 15 with Playwright

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-


      - name: Install dependencies
        run: npm install


      - name: Build Next.js project
        run: npm run build

      # 서버 실행 및 대기
      - name: Start Next.js server
        run: |
          npm run start &  # 서버를 백그라운드에서 실행
          npx wait-on http://localhost:3000  # 서버가 준비될 때까지 대기

      - name: Install Playwright Browsers
        run: npx playwright install

      - name: Run Playwright tests
        run: npx playwright test